kotlin.code.style=official
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4048m
org.gradle.dependency.verification.console=verbose
org.gradle.welcome=never
org.gradle.configuration-cache=false
org.gradle.configuration-cache.problems=warn
org.gradle.console=verbose