# Spotless Configuration

# KtLint Configuration
ktlint.version=0.50.0

# Kotlin Configuration
kotlin.exclude=**/build/**/*.kt,**/generated/**/*.kt

# Kotlin Gradle Configuration
kotlinGradle.exclude=**/build/**/*.gradle.kts

# Misc Format Configuration
misc.targets=*.md,.gitignore,*.yaml,*.yml

# XML Format Configuration
xml.format.enabled=true
xml.exclude=**/build/**/*.xml
xml.indent.spaces=4

# License Header Configuration
license.header.path=config/spotless/copyright.kt

# Editor Config
editorconfig.path=config/spotless/.editorconfig